# Generated by Django 5.0.6 on 2024-11-19 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='site_setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=200)),
                ('site_url', models.CharField(max_length=200)),
                ('about_us', models.TextField()),
                ('address', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('copy_right', models.TextField()),
                ('site_logo', models.ImageField(upload_to='Side_Logo/')),
                ('Main_setting', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Site_Settings',
            },
        ),
    ]
