# Generated by Django 5.0.6 on 2024-11-19 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='concertModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('SingarName', models.CharField(max_length=100)),
                ('lenth', models.IntegerField()),
                ('poster', models.ImageField(upload_to='concertImage/')),
            ],
        ),
        migrations.CreateModel(
            name='locationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=500)),
                ('phone', models.CharField(max_length=11)),
                ('capcity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='timeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StartDateTime', models.DateTimeField()),
                ('Seats', models.IntegerField()),
                ('status', models.IntegerField(choices=[(1, 'Selling ticket Start'), (2, 'Selling ticket Ended'), (3, 'This Sance Canceled'), (4, 'Ticket Selling is open')])),
                ('concertModel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticketSales.concertmodel')),
                ('locationModel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticketSales.locationmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ticketModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tecketImage', models.ImageField(upload_to='ticketimages/')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('ProfileModel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.profilemodel')),
                ('timeModel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticketSales.timemodel')),
            ],
        ),
    ]
