# Generated by Django 5.1.3 on 2024-11-22 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketSales', '0002_alter_ticketmodels_profilemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='timemodel',
            name='price',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=100),
        ),
    ]
