# Generated by Django 5.1.3 on 2024-11-23 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketSales', '0003_timemodel_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timemodel',
            name='price',
        ),
        migrations.AddField(
            model_name='concertmodel',
            name='price',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=100),
        ),
    ]
