# Generated by Django 5.1.3 on 2024-11-25 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketSales', '0004_remove_timemodel_price_concertmodel_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='timemodel',
            name='remaining_seats',
            field=models.IntegerField(default=0),
        ),
    ]
