# Generated by Django 5.1.3 on 2024-11-22 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0002_alter_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='final_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
