# Generated by Django 5.1.3 on 2024-11-23 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0003_alter_orderdetail_final_price'),
        ('ticketSales', '0004_remove_timemodel_price_concertmodel_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='concert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_details', to='ticketSales.concertmodel'),
        ),
    ]
