# Generated by Django 5.1.3 on 2024-11-25 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0004_orderdetail_concert'),
        ('ticketSales', '0005_timemodel_remaining_seats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='concert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_details', to='ticketSales.concertmodel'),
        ),
    ]
