# Generated by Django 5.1.3 on 2024-11-26 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0005_alter_orderdetail_concert'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='time',
        ),
    ]
