# Generated by Django 5.1.3 on 2024-11-26 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0006_remove_orderdetail_time'),
        ('ticketSales', '0005_timemodel_remaining_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='seats',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_details', to='ticketSales.timemodel'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='seat_count',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
